//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novus.Properties.EmbeddedResources", typeof(EmbeddedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4A4D98.
        /// </summary>
        internal static string g_pGCHeap {
            get {
                return ResourceManager.GetString("g_pGCHeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 348C00.
        /// </summary>
        internal static string Ofs_IsHeapPointer {
            get {
                return ResourceManager.GetString("Ofs_IsHeapPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8B 41 28 A8 02 74 ? 48 8B 40 26 C3.
        /// </summary>
        internal static string Sig_GetEEClass {
            get {
                return ResourceManager.GetString("Sig_GetEEClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0F B6 41 02 48 8B D1 0F B7 09.
        /// </summary>
        internal static string Sig_GetMemberDef {
            get {
                return ResourceManager.GetString("Sig_GetMemberDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8B 01 A8 02 75 ? C3.
        /// </summary>
        internal static string Sig_GetMethodTable {
            get {
                return ResourceManager.GetString("Sig_GetMethodTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0F B7 41 06 A8 20 74 ?.
        /// </summary>
        internal static string Sig_GetNativeCode {
            get {
                return ResourceManager.GetString("Sig_GetNativeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 48 8B 41 28 48 8B D9.
        /// </summary>
        internal static string Sig_GetNativeLayoutInfo {
            get {
                return ResourceManager.GetString("Sig_GetNativeLayoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 EC 38 0F B7 41 06.
        /// </summary>
        internal static string Sig_GetRVA {
            get {
                return ResourceManager.GetString("Sig_GetRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 8B 41 0C 48 8B D9.
        /// </summary>
        internal static string Sig_GetSize {
            get {
                return ResourceManager.GetString("Sig_GetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 8A 41 03.
        /// </summary>
        internal static string Sig_IsPointingToNativeCode {
            get {
                return ResourceManager.GetString("Sig_IsPointingToNativeCode", resourceCulture);
            }
        }
    }
}
