//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novus.Properties.EmbeddedResources", typeof(EmbeddedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        internal static string E_Cmd {
            get {
                return ResourceManager.GetString("E_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string E_Explorer {
            get {
                return ResourceManager.GetString("E_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.exe.
        /// </summary>
        internal static string E_File {
            get {
                return ResourceManager.GetString("E_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to python.exe.
        /// </summary>
        internal static string E_Py {
            get {
                return ResourceManager.GetString("E_Py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symchk.
        /// </summary>
        internal static string E_Symchk {
            get {
                return ResourceManager.GetString("E_Symchk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magic.mgc.
        /// </summary>
        internal static string F_Magic {
            get {
                return ResourceManager.GetString("F_Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] File_types {
            get {
                object obj = ResourceManager.GetObject("File_types", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask.
        /// </summary>
        internal static string K_Mask {
            get {
                return ResourceManager.GetString("K_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string K_Name {
            get {
                return ResourceManager.GetString("K_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string K_Offset {
            get {
                return ResourceManager.GetString("K_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pattern.
        /// </summary>
        internal static string K_Pattern {
            get {
                return ResourceManager.GetString("K_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://msdl.microsoft.com/download/symbols/.
        /// </summary>
        internal static string MicrosoftSymbolServer {
            get {
                return ResourceManager.GetString("MicrosoftSymbolServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.0.7.
        /// </summary>
        internal static string RequiredVersion {
            get {
                return ResourceManager.GetString("RequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC 40 44 8B 05.
        /// </summary>
        internal static string Sig_AllocObject {
            get {
                return ResourceManager.GetString("Sig_AllocObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC 20 0F B6 41 02 4C 8B C1 48 8B F1.
        /// </summary>
        internal static string Sig_GetIL {
            get {
                return ResourceManager.GetString("Sig_GetIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0F B6 41 02 48 8B D1 0F B7 09.
        /// </summary>
        internal static string Sig_GetMemberDef {
            get {
                return ResourceManager.GetString("Sig_GetMemberDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8B 01 A8 02 75 01.
        /// </summary>
        internal static string Sig_GetMethodTable {
            get {
                return ResourceManager.GetString("Sig_GetMethodTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0F B7 41 06 A8 20 74 13.
        /// </summary>
        internal static string Sig_GetNativeCode {
            get {
                return ResourceManager.GetString("Sig_GetNativeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 48 8B 41 28 48 8B D9.
        /// </summary>
        internal static string Sig_GetNativeLayoutInfo {
            get {
                return ResourceManager.GetString("Sig_GetNativeLayoutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 30 0F B7 41 06.
        /// </summary>
        internal static string Sig_GetRVA {
            get {
                return ResourceManager.GetString("Sig_GetRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 8B 41 0C 48 8D 1D.
        /// </summary>
        internal static string Sig_GetSize {
            get {
                return ResourceManager.GetString("Sig_GetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 EC 28 F7 41 ? ? ? ? ? 4C 8B D9.
        /// </summary>
        internal static string Sig_GetStaticAddr {
            get {
                return ResourceManager.GetString("Sig_GetStaticAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 EC 28 48 8B CA 41 0F B6 D0 E8 ? ? ? ? 48 85 C0 0F 95 C0 48 83 C4 28 C3 CC CC CC CC CC 4C 8B 02 33 C9 49 83 E0 F8 41 39 08 7D 0B 8B 4A 08 41 0F B7 00 48 0F AF C8 41 8B 40 04 48 03 C1 48 3B 05 ? ? ? ? 0F 93 C0 C3 CC CC CC CC CC 40 53.
        /// </summary>
        internal static string Sig_IsHeapPointer {
            get {
                return ResourceManager.GetString("Sig_IsHeapPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 B8 ? ? ? ? 48 8B D9 66 85 01.
        /// </summary>
        internal static string Sig_IsPointingToNativeCode {
            get {
                return ResourceManager.GetString("Sig_IsPointingToNativeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 53 48 83 EC 20 48 8B D9 E8 ? ? ? ? 84 C0 74 0D.
        /// </summary>
        internal static string Sig_Reset {
            get {
                return ResourceManager.GetString("Sig_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC 20 48 8B FA 48 8B F1 E8 ? ? ? ? 48 8B CE.
        /// </summary>
        internal static string Sig_SetEntryPoint {
            get {
                return ResourceManager.GetString("Sig_SetEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g_pGCHeap.
        /// </summary>
        internal static string Sym_GCHeap {
            get {
                return ResourceManager.GetString("Sym_GCHeap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKS::GCHeap::IsHeapPointer.
        /// </summary>
        internal static string Sym_IsHeapPointer {
            get {
                return ResourceManager.GetString("Sym_IsHeapPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36.
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
